In [1]:
import pandas as pd
import openpyxl
import plotly.graph_objects as go
import plotly.express as px
import numpy as np

In [2]:
covid_data = pd.read_excel('owid-covid-data.xlsx', engine='openpyxl')

# Select only the European countries
covid_data_europe = covid_data[covid_data['continent'] == 'Europe']

In [3]:
covid_data_europe['date'] = pd.to_datetime(covid_data_europe['date'], format='%Y-%m-%d')

<ipython-input-3-9e7d8e397f80>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  covid_data_europe['date'] = pd.to_datetime(covid_data_europe['date'], format='%Y-%m-%d')

In [4]:
covid_data_europe.drop('tests_units',axis=1, inplace=True)

C:\Users\PC\anaconda3\lib\site-packages\pandas\core\frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [5]:
covid_data_europe[covid_data_europe.iloc[:,4:] < 0] = np.nan

<ipython-input-5-dbc404ff4ef8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  covid_data_europe[covid_data_europe.iloc[:,4:] < 0] = np.nan
C:\Users\PC\anaconda3\lib\site-packages\pandas\core\frame.py:3089: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._where(-key, value, inplace=True)

In [6]:
mean_europe = covid_data_europe.groupby('date').sum().reset_index()

In [7]:
covid_data_europe

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
795,ALB,Europe,Albania,2020-02-25,NaN,NaN,NaN,NaN,NaN,NaN,...,11803.431,1.1,304.195,10.08,7.1,51.2,NaN,2.89,78.57,0.795
796,ALB,Europe,Albania,2020-02-26,NaN,NaN,NaN,NaN,NaN,NaN,...,11803.431,1.1,304.195,10.08,7.1,51.2,NaN,2.89,78.57,0.795
797,ALB,Europe,Albania,2020-02-27,NaN,NaN,NaN,NaN,NaN,NaN,...,11803.431,1.1,304.195,10.08,7.1,51.2,NaN,2.89,78.57,0.795
798,ALB,Europe,Albania,2020-02-28,NaN,NaN,NaN,NaN,NaN,NaN,...,11803.431,1.1,304.195,10.08,7.1,51.2,NaN,2.89,78.57,0.795
799,ALB,Europe,Albania,2020-02-29,NaN,NaN,NaN,NaN,NaN,NaN,...,11803.431,1.1,304.195,10.08,7.1,51.2,NaN,2.89,78.57,0.795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74102,VAT,Europe,Vatican,2021-03-17,27.0,0.0,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.12,NaN
74103,VAT,Europe,Vatican,2021-03-18,27.0,0.0,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.12,NaN
74104,VAT,Europe,Vatican,2021-03-19,27.0,0.0,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.12,NaN
74105,VAT,Europe,Vatican,2021-03-20,27.0,0.0,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.12,NaN
74106,VAT,Europe,Vatican,2021-03-21,27.0,0.0,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.12,NaN

In [8]:
covid_data_europe = pd.concat([covid_data_europe, mean_europe], axis=0)

In [9]:
covid_data_europe.to_excel('covid_data_europe.xlsx')